# Generated by Django 2.1.4 on 2020-05-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.DeleteModel(
            name='FriendLink',
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
